BASE_DIR : "unlearning"
DEVICE : 'cpu'
SEED : 42
DATA_PATH: 'data'
MODEL_DIR: 'models'

directory:
  RESULT_PATH: 'results'
  LOG_PATH: 'logs'
  LOGGER_PATH: 'logger.log'

data:
  num_workers: 6
  num_classes: 8
  BATCH_SIZE : 512

model:
  name: 'resnet18'
  model_args:
    num_classes: 8
  checkpoint: 'neurips-submission/model_base_celeba.pt'

trainer :
  verbose: True
  train: False
  
  
  log_freq: 1
  epochs: 40
  optimizer: 
    type: 'AdamW'
    lr: 0.0003
    weight_decay: 1
    betas: [0.9, 0.999]

  scheduler: 
    type: 'CosineAnnealingLR'
    T_max: 40

scratch_trainer :
  verbose: True
  train: False
  
  log_freq:  1
  epochs: 0
  
  optimizer: 
    type: 'AdamW'
    lr: 0.0003
    weight_decay: 1
    betas: [0.9, 0.999]

  scheduler: 
    type: 'CosineAnnealingLR'
    T_max: 40


finetune:
  verbose: True
  train: True
  
  log_freq: 1
  epochs: 4
  
  optimizer: 
    type: 'AdamW'
    lr: 0.0003
    weight_decay: 1
    betas: [0.9, 0.999]

  scheduler: 
    type: 'CosineAnnealingLR'
    T_max: 4