BASE_DIR : "unlearning"
DEVICE : 'cuda:0'
SEED : 42
BATCH_SIZE : 64
DATA_PATH: 'data'
MODEL_DIR: 'models'

directory:
  RESULT_PATH: 'results'
  LOG_PATH: 'logs'
  LOGGER_PATH: 'logger.log'

data:
  num_workers: 6
  rf_split: [0.1, 0.9]
  num_classes: 4

model:
  name: 'resnet18' #IdentitySpoof #MTLResNet resnet50 ClassSpecificResNet NormConstrainedResNet
  model_args:
    # num_heads: 40 #40
    num_classes: 4
  # model_args:
  #   num_classes: 10
  #   block_config: [[3,4,1],[2,8,2],[2,16,2]] 
    
  # checkpoint: "/research/hal-gaudisac/unlearning/models/weights_resnet18_cifar10.pth"
#trainer_checkpoint: "/research/hal-gaudisac/unlearning/models/model_resnet50_20.pt"
trainer :
  #checkpoint: 'models/model_unl.pt'
  verbose: False
  train: True
  
  log_freq: 10
  epochs: 60

  # optimizer: 
  #   type: 'SGD'
  #   lr: 0.1
  #   momentum: 0.9
  #   weight_decay: 0.00005
  
  optimizer: 
    type: 'AdamW'
    lr: 0.003
    weight_decay: 0.00001
    betas: [0.9, 0.999]

  scheduler: 
    type: 'CosineAnnealingLR'
    T_max: 60

attack_model:
  name: 'MLP-grad-mia'
  type: 'MiaModel'
  charecterstic: 'gradients'
  folds: 5
  model_args:
    model_config: [512,256,128,64,16,8]
    num_classes: 2
    
attack_trainer: 

  name: 'mia trainer'
  verbose: False
  epochs: 300
  log_freq: 50

  # optimizer: 
  #   type: 'SGD'
  #   lr: 0.1
  #   momentum: 0.9
  #   weight_decay: 0.0001
  optimizer: 
    type: 'AdamW'
    lr: 0.0003
    weight_decay: 0.00001
    betas: [0.9, 0.999]

  scheduler: 
    type: 'CosineAnnealingLR'
    T_max: 300

finetune :
  verbose: True
  train: True
  
  log_freq: 5
  epochs: 30

  # optimizer: 
  #   type: 'AdamW'
  #   lr: 0.015
  #   weight_decay: 0.00001
  #   betas: [0.9, 0.999]

  optimizer: 
    type: 'AdamW'
    lr: 0.003
    weight_decay: 0.00001
    betas: [0.9, 0.999]

  scheduler: 
    type: 'CosineAnnealingLR'
    T_max: 30

# scratch_trainer_checkpoint: '/research/hal-gaudisac/unlearning/models/scratch_resnet18.pt'
#trainer_checkpoint: '/research/hal-gaudisac/unlearning/models/model_unl.pt'









#model:
#  name: 'ResNet' 
#  model_args:
#    block_config: [[3,64,1],[2,128,2],[2,256,2],[2,512,2]] [(1,8,1),(1,16,2),(1,32,2)] #model with 3 blocks of 16 channels with a stride of 1 and 2 blocks of 32 and 64 channels with a stride of 2 

#training :
#  checkpoint: '/research/hal-gaudisac/unlearning/models/weigths_ResNet_3x64x1-2x128x2-2x256x2-2x512x2.pt'
#  checkpoint: '/research/hal-gaudisac/unlearning/models/weigths_ResNet_1x8x1-1x16x2-1x32x2.pt'


#attack_model:
#  name: 'MLP-grad-mia'
#  type: 'MiaModel' LogisticRegression GradientBoostingClassifier
#  charecterstic: 'gradient' 
#  model_args:
#    model_config: [512,256,128,64,32,16,8] num_iters=1000