name: unl2
channels:
  - pytorch-nightly
  - nvidia
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - pip:
      - cvxpy==1.3.2
      - docker-pycreds==0.4.0
      - ecos==2.0.12
      - einops==0.6.1
      - folktables==0.0.12
      - gitdb==4.0.10
      - gitpython==3.1.31
      - huggingface-hub==0.14.1
      - kaleido==0.2.1
      - osqp==0.6.3
      - pathtools==0.1.2
      - qbittorrent==0.1.6
      - qdldl==0.1.7
      - safetensors==0.3.1
      - scs==3.2.3
      - sentry-sdk==1.21.0
      - setproctitle==1.3.2
      - setuptools==68.0.0
      - smmap==5.0.0
      - tikzplotlib==0.10.1
      - timm==0.9.2
      - wandb==0.15.0
      - webcolors==1.13
      - wget==3.2
